import { display_studio } from "@/assets/image"
export const studioList = [
    {
        name: "Corner Music Studio",
        img: display_studio,
        rating: { star: 4.2, resp: 872 },
        location: "Lowokwaru, Malang",
        realPrice: 70000,
        price: 50000,
    },
    {
        name: "Corner Music Studio",
        img: display_studio,
        rating: { star: 4.2, resp: 872 },
        location: "Lowokwaru, Malang",
        realPrice: 70000,
        price: 50000,
    },
    {
        name: "Corner Music Studio",
        img: display_studio,
        rating: { star: 4.2, resp: 872 },
        location: "Lowokwaru, Malang",
        realPrice: 70000,
        price: 50000,
    },
    {
        name: "Corner Music Studio",
        img: display_studio,
        rating: { star: 4.2, resp: 872 },
        location: "Lowokwaru, Malang",
        realPrice: 70000,
        price: 50000,
    },
    {
        name: "Corner Music Studio",
        img: display_studio,
        rating: { star: 4.2, resp: 872 },
        location: "Lowokwaru, Malang",
        realPrice: 70000,
        price: 50000,
    },
    {
        name: "Corner Music Studio",
        img: display_studio,
        rating: { star: 4.2, resp: 872 },
        location: "Lowokwaru, Malang",
        realPrice: 70000,
        price: 50000,
    },
    {
        name: "Corner Music Studio",
        img: display_studio,
        rating: { star: 4.2, resp: 872 },
        location: "Lowokwaru, Malang",
        realPrice: 70000,
        price: 50000,
    },
]